static const char interlace_glsl_shader_raw[] = 
"#ifdef FRAGMENT_SHADER\n"
"\n"
"in vec4 PSin_p;\n"
"in vec2 PSin_t;\n"
"in vec4 PSin_c;\n"
"\n"
"uniform vec4 ZrH;\n"
"\n"
"layout(binding = 0) uniform sampler2D TextureSampler;\n"
"\n"
"layout(location = 0) out vec4 SV_Target0;\n"
"\n"
"\n"
"// The source row of an output row, as an offset to its own coordinate. A\n"
"// half-height field (ZrH.w > 0) was stretched twice into the source, and\n"
"// its line's block of rows spans two frame lines, since the field's rows\n"
"// are half a frame line apart: the line takes the first half of the block,\n"
"// and the second half is the other field's positions. The output's rows\n"
"// between the field's are the mean of the two around them, read with the\n"
"// linear sampler at the edge between them (the source holds each field\n"
"// row twice, so a row's centre reads that row alone). A full-height field\n"
"// reads its own row. yb is the frame line with the row's place in it, l\n"
"// the line.\n"
"float line_rows(float yb, int l, float y, float rcp_h)\n"
"{\n"
"	if (ZrH.w > 0.0f)\n"
"	{\n"
"		const float place = ((yb - float(l)) * ZrH.w - 0.5f) * 0.5f; // the row's place in the line, in field rows\n"
"		const float row  = floor(float(l >> 1) * ZrH.w) + floor(place);\n"
"		return (2.0f * row + 0.5f + 3.0f * (place - floor(place)) - y) * rcp_h;\n"
"	}\n"
"	return 0.0f;\n"
"}\n"
"\n"
"// Weave shader\n"
"void ps_main0()\n"
"{\n"
"	int idx   = int(ZrH.x);          // buffer index passed from CPU\n"
"	int field = idx & 1;             // current field\n"
"	// A frame line is |ZrH.w| rows at scale; the rows of a line come from one\n"
"	// field, so a field drawn a half line off the other weaves by lines as it\n"
"	// does natively, not by rows; line_rows places them.\n"
"	float yb = gl_FragCoord.y / abs(ZrH.w);\n"
"	int   l  = int(yb);\n"
"\n"
"	if ((l & 1) == field)\n"
"		SV_Target0 = textureLod(TextureSampler, vec2(PSin_t.x, PSin_t.y + line_rows(yb, l, gl_FragCoord.y, ZrH.y)), 0);\n"
"	else\n"
"		discard;\n"
"}\n"
"\n"
"\n"
"// Bob shader\n"
"void ps_main1()\n"
"{\n"
"	SV_Target0 = textureLod(TextureSampler, PSin_t, 0);\n"
"}\n"
"\n"
"\n"
"// Blend shader\n"
"void ps_main2()\n"
"{\n"
"	vec2 vstep = vec2(0.0f, ZrH.y * abs(ZrH.w)); // the lines above and below, at scale\n"
"	vec4 c0 = textureLod(TextureSampler, PSin_t - vstep, 0);\n"
"	vec4 c1 = textureLod(TextureSampler, PSin_t, 0);\n"
"	vec4 c2 = textureLod(TextureSampler, PSin_t + vstep, 0);\n"
"\n"
"	SV_Target0 = (c0 + c1 * 2.0f + c2) / 4.0f;\n"
"}\n"
"\n"
"\n"
"// MAD shader - buffering\n"
"void ps_main3()\n"
"{\n"
"	// We take half the lines from the current frame and stores them in the MAD frame buffer.\n"
"	// the MAD frame buffer is split in 2 consecutive banks of 2 fields each, the fields in each bank\n"
"	// are interleaved (top field at even lines and bottom field at odd lines).\n"
"	// When the source texture has an odd vres, the first line of bank 1 would be an odd index\n"
"	// causing the wrong lines to be discarded, so a vertical offset (lofs) is added to the vertical\n"
"	// position of the destination texture to force the proper field alignment\n"
"\n"
"	int  idx    = int(ZrH.x);                                // buffer index passed from CPU\n"
"	int  bank   = idx >> 1;                                  // current bank\n"
"	int  field  = idx & 1;                                   // current field\n"
"	int  vres   = int(ZrH.z) >> 1;                           // vertical resolution of source texture\n"
"	int  lofs   = ((((vres + 1) >> 1) << 1) - vres) & bank;  // line alignment offset for bank 1\n"
"	float yb = (gl_FragCoord.y + float(lofs)) / abs(ZrH.w);             // frame line at scale (|ZrH.w| rows each; the bank is the source's height, half of ZrH.z)\n"
"	int   l  = int(yb);\n"
"\n"
"	// if the line belongs to the current field we update its rows, otherwise we\n"
"	// leave the old rows in the destination buffer (full-height fields; half-height\n"
"	// ones are kept whole, see mad_fields)\n"
"	if ((l & 1) == field)\n"
"		SV_Target0 = textureLod(TextureSampler, PSin_t, 0);\n"
"	else\n"
"		discard;\n"
"}\n"
"\n"
"\n"
"// MAD shader - reconstruction\n"
"// The adaptive reconstruction of half-height fields. The buffer holds the last\n"
"// four fields whole, one to a quarter of it, the current one in slot idx. A\n"
"// field of parity p drew its line j at frame line 2j + p, and at a scale of\n"
"// two or more it holds rows of its own for the frame line after it as well:\n"
"// its rows cover the output two rows each from row p * block. At 1x the line\n"
"// after it is between two of its rows and reads their mean.\n"
"// The current field's lines are taken as they are. Between them, where the\n"
"// picture holds still, the previous field's line (weave); where it moves, the\n"
"// current field's own picture there, of the same instant.\n"
"// Motion is measured once per native pixel, on the first row of its block, in\n"
"// luma: the lines above and below against the same field two back, or the\n"
"// line itself against its field two back; each fragment blends by it.\n"
"vec4 mad_field(int back, float y, float x)\n"
"{\n"
"	int   idx    = int(ZrH.x);\n"
"	float slot_h = ZrH.z * 0.5f;\n"
"	int   slot   = (idx - back) & 3;\n"
"	int   par    = (idx ^ back) & 1;\n"
"	float rel    = (y - float(par) * ZrH.w) * 0.5f;\n"
"	float r      = clamp(((ZrH.w >= 2.0f) ? floor(rel) : rel) + 0.5f, 0.5f, slot_h - 0.5f);\n"
"	return textureLod(TextureSampler, vec2(x, (float(slot) * slot_h + r) / (ZrH.z * 2.0f)), 0);\n"
"}\n"
"\n"
"float mad_luma(vec4 c)\n"
"{\n"
"	return dot(c.rgb, vec3(0.299f, 0.587f, 0.114f));\n"
"}\n"
"\n"
"void mad_fields()\n"
"{\n"
"	float block = ZrH.w;\n"
"	int   field = int(ZrH.x) & 1;\n"
"	float y     = floor(gl_FragCoord.y);\n"
"	int   l     = int(y / block);\n"
"\n"
"	vec4 cur = mad_field(0, y, PSin_t.x);\n"
"	if ((l & 1) == field)\n"
"	{\n"
"		SV_Target0 = cur;\n"
"		return;\n"
"	}\n"
"\n"
"	float yl = float(l) * block;\n"
"	float xc = PSin_t.x + dFdx(PSin_t.x) * ((floor(gl_FragCoord.x / block) + 0.5f) * block - gl_FragCoord.x);\n"
"	float mh = abs(mad_luma(mad_field(0, yl - block, xc)) - mad_luma(mad_field(2, yl - block, xc)));\n"
"	float ml = abs(mad_luma(mad_field(0, yl + block, xc)) - mad_luma(mad_field(2, yl + block, xc)));\n"
"	float mc = abs(mad_luma(mad_field(1, yl, xc)) - mad_luma(mad_field(3, yl, xc)));\n"
"	float moving = smoothstep(0.01f, 0.03f, max(max(mh, ml), mc));\n"
"\n"
"	SV_Target0 = mix(mad_field(1, y, PSin_t.x), cur, moving);\n"
"}\n"
"\n"
"void ps_main4()\n"
"{\n"
"	if (ZrH.w > 0.0f)\n"
"	{\n"
"		mad_fields();\n"
"		return;\n"
"	}\n"
"\n"
"	// we use the contents of the MAD frame buffer to reconstruct the missing lines from the current field.\n"
"\n"
"	int   idx          = int(ZrH.x);                         // buffer index passed from CPU\n"
"	int   field        = idx & 1;                            // current field\n"
"	float sensitivity  = 0.08f;                                 // higher values mean more likely to use weave\n"
"	vec3  motion_thr   = vec3(1.0, 1.0, 1.0) * sensitivity;  //\n"
"	vec2  bofs         = vec2(0.0f, 0.5f);                   // position of the bank 1 relative to source texture size\n"
"	vec2  vscale       = vec2(1.0f, 0.5f);                   // scaling factor from source to destination texture\n"
"	vec2  lofs         = vec2(0.0f, ZrH.y * abs(ZrH.w)) * vscale;         // distance between two adjacent lines relative to source texture size\n"
"	vec2  iptr         = PSin_t * vscale;                    // pointer to the current pixel in the source texture\n"
"\n"
"	vec2 p_t0; // pointer to current pixel (missing or not) from most recent frame\n"
"	vec2 p_t1; // pointer to current pixel (missing or not) from one frame back\n"
"	vec2 p_t2; // pointer to current pixel (missing or not) from two frames back\n"
"	vec2 p_t3; // pointer to current pixel (missing or not) from three frames back\n"
"\n"
"	switch (idx)\n"
"	{\n"
"		case 1:\n"
"			p_t0 = iptr;\n"
"			p_t1 = iptr;\n"
"			p_t2 = iptr + bofs;\n"
"			p_t3 = iptr + bofs;\n"
"			break;\n"
"		case 2:\n"
"			p_t0 = iptr + bofs;\n"
"			p_t1 = iptr;\n"
"			p_t2 = iptr;\n"
"			p_t3 = iptr + bofs;\n"
"			break;\n"
"		case 3:\n"
"			p_t0 = iptr + bofs;\n"
"			p_t1 = iptr + bofs;\n"
"			p_t2 = iptr;\n"
"			p_t3 = iptr;\n"
"			break;\n"
"		default:\n"
"			p_t0 = iptr;\n"
"			p_t1 = iptr + bofs;\n"
"			p_t2 = iptr + bofs;\n"
"			p_t3 = iptr;\n"
"			break;\n"
"	}\n"
"\n"
"\n"
"	// calculating motion, only relevant for missing lines where the center line is pointed\n"
"	// by p_t1\n"
"\n"
"	vec4 hn = textureLod(TextureSampler, p_t0 - lofs, 0); // new high pixel\n"
"	vec4 cn = textureLod(TextureSampler, p_t1, 0);        // new center pixel\n"
"	vec4 ln = textureLod(TextureSampler, p_t0 + lofs, 0); // new low pixel\n"
"\n"
"	vec4 ho = textureLod(TextureSampler, p_t2 - lofs, 0); // old high pixel\n"
"	vec4 co = textureLod(TextureSampler, p_t3, 0);        // old center pixel\n"
"	vec4 lo = textureLod(TextureSampler, p_t2 + lofs, 0); // old low pixel\n"
"\n"
"	vec3 mh = hn.rgb - ho.rgb; // high pixel motion\n"
"	vec3 mc = cn.rgb - co.rgb; // center pixel motion\n"
"	vec3 ml = ln.rgb - lo.rgb; // low pixel motion\n"
"\n"
"	mh = max(mh, -mh) - motion_thr;\n"
"	mc = max(mc, -mc) - motion_thr;\n"
"	ml = max(ml, -ml) - motion_thr;\n"
"\n"
"	#if 1 // use this code to evaluate each color motion separately\n"
"		float mh_max = max(max(mh.x, mh.y), mh.z);\n"
"		float mc_max = max(max(mc.x, mc.y), mc.z);\n"
"		float ml_max = max(max(ml.x, ml.y), ml.z);\n"
"	#else // use this code to evaluate average color motion\n"
"		float mh_max = mh.x + mh.y + mh.z;\n"
"		float mc_max = mc.x + mc.y + mc.z;\n"
"		float ml_max = ml.x + ml.y + ml.z;\n"
"	#endif\n"
"\n"
"\n"
"	// selecting deinterlacing output\n"
"\n"
"	if ((int(gl_FragCoord.y / abs(ZrH.w)) & 1) == field)\n"
"	{\n"
"		// output line present on current field\n"
"		SV_Target0 = textureLod(TextureSampler, p_t0, 0);\n"
"	}\n"
"	else if ((iptr.y > 0.5f - lofs.y) || (iptr.y < 0.0 + lofs.y))\n"
"	{\n"
"		// top and bottom lines are always weaved\n"
"		SV_Target0 = cn;\n"
"	}\n"
"	else\n"
"	{\n"
"		// missing line needs to be reconstructed\n"
"		if(((mh_max > 0.0f) || (ml_max > 0.0f)) || (mc_max > 0.0f))\n"
"			// high motion -> interpolate pixels above and below\n"
"			SV_Target0 = (hn + ln) / 2.0f;\n"
"		else\n"
"			// low motion -> weave\n"
"			SV_Target0 = cn;\n"
"	}\n"
"}\n"
"\n"
"#endif\n"
;
